name: CI for Pull Requests/Branches

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.22

    - name: Install OS Dependencies
      run: sudo apt-get install gcc libgtk-3-dev libayatana-appindicator3-dev libxxf86vm-dev
    
    - name: Install Dependencies
      run: go get -v ./...

    - name: Build
      run: make build

    - name: Test
      run: make test
